name: java_output

on:
  workflow_dispatch:

jobs:
  get-output-from-file:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.store-output.outputs.str1 }}
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: morelandc/java-program
      - name: Store file output
        id: store-output
        run: ${{ steps.store-output.outputs.str1="n10<" }} 
      - name: Cat file
        run: cat "$GITHUB_OUTPUT"
      - name: Access output
        run: echo "Greeting is ${{ steps.store-output.outputs.str1 }}"

  pass-to-file:
    runs-on: ubuntu-latest
    needs: get-output-from-file
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: morelandc/java-files
      - name: Pass output as parameter
        run: java check-string.java "${{ needs.get-output-from-file.outputs.output1 }}"
